### ISSUE TITLE
Fix potential partial matching issue in `gmse_apply`

### ISSUE THREAD

**Issue by bradduthie** [ConFooBio/gmse#53]
Just to head off any potential issues in `gmse_apply`, several places in the code use the format `sim_list$element_name` rather than `sim_list[["element_name"]]. The latter is more robust because it prohibits partial matching. Hence in [gmse_apply.R](https://github.com/ConFooBio/gmse/blob/master/R/gmse_apply.R), this should be changed.

**Comment by jejoenje** [comment]
@bradduthie, just to check if I understand you correctly, as a test I've replaced all the `sim_list$element` references in `swap_old_gmse()`. [See my latest commit to branch `jeroen`](https://github.com/ConFooBio/gmse/compare/jeroen).

Apols if this doesn't help, but if it does I'm happy to make further suggested changes.

**Comment by bradduthie** [comment]
@jejoenje Yeah, this is exactly what I meant -- before the next version of GMSE, I'll try to remind myself to make sure these get changed.

**Comment by bradduthie** [comment]
Closing this comment, as the issue is now fully addressed in commit [b119cd5770fbd9c717fb56907ad7ff3f64e12342](https://github.com/ConFooBio/gmse/commit/b119cd5770fbd9c717fb56907ad7ff3f64e12342)
