### ISSUE TITLE
Some conditions result in biased observations

### ISSUE THREAD

**Issue by bradduthie** [ConFooBio/gmse#73]
Because managers return to their 'home' cell after estimating population size, when `res_observe_type = 0`, `times_observe = 1`, and `agent_view` is less than the full size of the landscape, the manager will be sampling the density of the population from the same position on the landscape each time. In a situation like @mattnuttall00 is running where resources don't move, this causes a biased estimate of the population size (i.e., if you're repeatedly using tree density in the same local area and extrapolating to estimate tree density in the larger landscape, you will inevitably get a consistent bias with each repeated observation). I'm not sure if this is a bug or a feature, but it's something that we might want to think about.

**Comment by mattnuttall00** [comment]
This is really interesting, thanks @bradduthie! I hadn't realised (or just hadn't really thought) about the manager being based in an explicit location, and therefore beginning their observations from the same spatial point. This makes sense now. My initial thought is that this is a feature. I can envisage scenarios where you may want to introduce systematic bias into the observation process via a spatially biased sampling mechanism. If there are other ways that you have specifically designed where this can be introduced, then I guess this approach is not necessary.

**Comment by bradduthie** [comment]
Thanks @mattnuttall00 -- yes, I was slightly nervous when I saw the consistently biased estimates, but it now makes sense, and I agree it can be considered a feature. The pattern goes away as soon as you let the manager move at least once (as you would expect), or if the resources themselves are moving.  Perhaps it's just an interesting point to put in the documentation.

**Comment by bradduthie** [comment]
This issue is now mentioned in one of the vignettes.
